# -*- coding: utf-8 -*-
"""Muhammad Fazal - Practise Case Statistics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BvIadBB2SjpULeHu1BOVj0RoHoPWPw1V

# Muhammad Fazal Hildiansyah - DS2

## Import Library
> Hal pertama yg dilakukan adalah import library yang akan digunakan pada analisa kita
"""

# import pandas
import pandas as pd

# import scaler dari sckit-learn untuk scala point
from sklearn.preprocessing import MinMaxScaler

# import warning agar tidak muncul warning terus di google colab
import warnings
warnings.filterwarnings("ignore")

"""## Data extraction
> Setelah itu, mulai dari Data Pre-processing, start dari extract data dari source yg akan digunakan
"""

# Baca datasource dari CSV sesuai dengan case
df_raw = pd.read_csv('https://raw.githubusercontent.com/fazalh/fellowship-ds2-statistics/master/Seasons_Stats.csv')

# Ini merupakan data tambahan, karena nama team di dataset berupa singkatan
nba_abbreviation = pd.read_csv('https://raw.githubusercontent.com/fazalh/fellowship-ds2-statistics/master/nba-abbreviation.csv')

# Merge Data source dengan kepanjangan dari nama Team
df_raw = df_raw.merge(nba_abbreviation, how='left', on='Tm')

# Check data ada berapa column dan row
df_raw.shape

"""## Data Cleansing
> Lalu mulai bersihkan data mengikuti aturan yg berlaku
"""

# Aturan pertama hanya pakai data tahun 2017

df_satu = df_raw[(df_raw['Year'] == 2017)]

df_satu.shape

# Aturan kedua drop duplicates player

df_dua = df_satu.drop_duplicates(subset=['Player'])

df_dua.shape

# Check column mana yg paling banyak missing values

df_dua.isnull().sum().sort_values(ascending=False)

# Aturan ketiga adalah drop kolom yg banyak missing values

df_tiga = df_dua.drop(['blank2', 'blanl'], axis = 1)

df_tiga.shape

# Karena kolom 'blank2' dan 'blanl' sudah kita drop,
# selanjutnya cek kolom yg masih ada missing value

df_tiga[['3P%','FT%','2P%','eFG%','TOV%','FG%','FTr','3PAr','TS%']].describe()

# Jika kita melihat 2 angka dibelakang koma, maka hanya 'FG%' yang symmetric, dan kita bisa impute values dengan nilai rata-rata/mean
df_tiga['FG%'] = df_tiga['FG%'].fillna((df_tiga['FG%'].mean()))

# karena kecenderungan skew maka Kolom lainnya diisi dengan median
df = df_tiga.fillna(df_tiga.median())

# Check ulang apakah masih ada missing values

df.info()

"""## Data Analysis

> Setelah data sudah clean, baru memulai analisa sesuai dengan soal
"""

df.head()

"""### 1. Who is the youngest and oldest player in the NBA in 2017 for each (Tm) ?"""

# Define younget and oldest player by Team
youngest = df.groupby('Team')['Age', 'Player'].min()
oldest = df.groupby('Team')['Age', 'Player'].max()

# Rename column di tiap dataframe
youngest = youngest.rename(columns={'Age': 'Youngest Age', 'Player': 'Youngest Player'})
oldest = oldest.rename(columns={'Age': 'Oldest Age', 'Player': 'Oldest Player'})

# Merge kedua result diatas
satu = youngest.merge(oldest, how='left', on='Team')
satu

"""### 2. Which Player has the most minutes played (MP) in each position (Pos) ?"""

# Define player yang paling sering bermain
dua = df.groupby('Pos')['MP', 'Player'].max()

dua

# Case Joffrey Lauvergne, dilihat dari data_raw, ternyata lebih sering bermain di Posisi Center
# Saat pindah dari Oklahoma ke Bulls, Joffrey kembali ke posisi semula yaitu Center
# Dan saat research di web NBA, setelah pindah dari Buls ke Spurs, dia juga tetap di Center

df_raw[['Year', 'Team', 'Pos', 'MP']][df_raw['Player'] == 'Joffrey Lauvergne']

# Maka dengan mengubah posisi Joffrey menjadi Center, akan didapatkan hasil seperti ini
df.loc[df['Player'] == 'Joffrey Lauvergne', 'Pos'] = 'C'

df.groupby('Pos')['MP', 'Player'].max()

"""### 3. Which team has the highest average total rebound percentage (TRB%), assist percentage (AST%), steal percentage (STL%), and block percentage (BLK%)?

"""

# Define average grouped by Team
tiga = df.groupby('Team')['TRB%', 'AST%', 'STL%', 'BLK%'].mean()
print(tiga)
print('\r')

# print highest TRB
trb = tiga[tiga['TRB%'] == tiga['TRB%'].max()]
print('Highest Average Total Rebound Percentage is ' + trb.index[0])

# print highest AST
ast = tiga[tiga['AST%'] == tiga['AST%'].max()]
print('Highest Average Assist Percentage is ' + ast.index[0])

# print highest STL
stl = tiga[tiga['STL%'] == tiga['STL%'].max()]
print('Highest Average Steal Percentage is ' + stl.index[0])

# print highest BLK
blk = tiga[tiga['BLK%'] == tiga['BLK%'].max()]
print('Highest Average Block Percentage is ' + blk.index[0])

"""### 4. Who is the best player in your opinion based on his record stats? note: you can refer to variables point (PTS), assists, rebounds, or anything else. A combination of several variables would be nice."""

# Menurut saya, Pemain terbaik di NBA adalah yg memiliki gaya permainan yang baik seperti :
# 1. eFG% - Effective Field Goal Percentage. Sudah mencakup 2 point dan 3 point tembakan.
# 2. TOV% - Turnover Percentage. Kesalahan saat menguasai bola harus rendah agar tidak terjadi turnover, terlihat dari makin rendahnya TOV% makin baik.
# 3. PER - Player Efficiency Rating. Pemain yg paling effisien.
# 4. PTS - Point. Karena di Basket, pemain terbaik adalah pemain yg mencetak score, itu termasuk pertahanan terbaik loh.

# kita buat dataframe untuk soal nomor 4
best_player = df[['Player','eFG%','PER', 'PTS', 'TOV%']].reset_index()

# gunakan MinMaxScaler dengan range dari 0 - 1
scaler = MinMaxScaler(feature_range=(0,1))

# pisahkan number dan category
best_number = best_player[['eFG%','PER', 'PTS', 'TOV%']]
best_name = best_player['Player']

# run scaler dan jadikan dataframe presult
scaler.fit(best_number)
presult = pd.DataFrame(scaler.transform(best_number), columns=['eFG%','PER', 'PTS', 'TOV%'])

# Untuk TOV karena yg makin rendah makin baik, maka kita ganti scalanya dengan 1-value
presult['TOV%'] = 1 - presult['TOV%']

# Jumlahkan semua hasil parameter kolom score
presult['Score'] = presult.sum(axis=1)

# kita gabungkan dengan dataframe best_player dan sort values descending based on Score
pres = pd.concat([best_name, presult], axis=1, sort=False)
pres = pres.sort_values(by=['Score'], ascending=False)
print(pres.head())
print('\r')

print('My best player is ' + pres['Player'][pres['Score'] == pres['Score'].max()])

"""### 5. Which team has the best average stat record of their players? Note: you can refer to points, assists, rebounds, or anything else. A combination of several variables would be nice"""

# Menurut saya, Team terbaik di NBA adalah yg memiliki faktor permainan yang baik :
# 1. eFG% - Effective Field Goal Percentage. Sudah mencakup 2 point dan 3 point tembakan.
# 2. TOV% - Turnover Percentage. Kesalahan saat menguasai bola harus rendah agar tidak terjadi turnover, terlihat dari makin rendahnya TOV% makin baik.
# 3. ORB% - Offensive Rebound Percentage. Penguasaan daerah bawah ring lawan.
# 4. DRB% - Defensive Rebound Percentage. Penguasaan daerah bawah ring team.
# 5. FT% - Free Throw Percentage. Seberapa sering melakukan free throw dan dapat point.

# kita buat dataframe untuk soal nomor 5
best_team = df.groupby('Team')['eFG%','TOV%','ORB%','DRB%','FT%'].mean().reset_index()

# gunakan MinMaxScaler dengan range dari 0 - 1
scaler = MinMaxScaler(feature_range=(0,1))

# pisahkan number dan category
team_number = best_team[['eFG%','TOV%','ORB%','DRB%','FT%']]
team_name = best_team['Team']

# run scaler dan jadikan dataframe tresult
scaler.fit(team_number)
tresult = pd.DataFrame(scaler.transform(team_number), columns=['eFG%','TOV%','ORB%','DRB%','FT%'])

# Sama seperti no.4 untuk TOV karena yg makin rendah makin baik, maka kita ganti scalanya dengan 1-value
tresult['TOV%'] = 1 - tresult['TOV%']

# ikuti perhitungan 4 factor dari Dean Oliver
tresult['eFG%'] = (40/100*tresult['eFG%'])
tresult['TOV%'] = (25/100*tresult['TOV%'])
tresult['FT%'] = (15/100*tresult['FT%'])
tresult['RB'] = (20/100*((tresult['ORB%']+tresult['DRB%'])/2))

# assign the score
tresult['Score'] = tresult['eFG%'] + tresult['TOV%'] + tresult['FT%'] + tresult['RB']

# kita gabungkan dengan dataframe team_name dan sort values descending based on Score
tres = pd.concat([team_name, tresult], axis=1, sort=False)
tres = tres.sort_values(by=['Score'], ascending=False)
print(tres.head())
print('\r')

# Hasilnya adalah Boston Celtics, tetapi sayang sekali saat final kalah dengan Golden State Warriors
print('My best team is ' + tres['Team'][tres['Score'] == tres['Score'].max()])

"""## Finish

"""